### PR TITLE
Implement aggregate lifecycle helper functions

### LINKED ISSUE #71: Provide improved methods for AggregateLifecycle
### Scenario

* extension-kotlin version: any
* Axon Framework version: any
* Description of your use case: 

`AggregateLifecycle` should provide Kotlin-like API. Since relevant `AggregateLifecycle` methods are static,
there is no way to extend existing class, but we can define new top-level functions.

Relevant methods are:
- `apply` is a kotlin function on Any, we should name it for example `applyEvent`
- `createNew` should get reified class and a factory function

### PR DESCRIPTION
**Pull request by zambrovski**
fix #71

### CODE REVIEW

**Review by smcvb — CHANGES_REQUESTED** [review]
What is provided looks fine, but I am uncertain why you haven't added the other static operations from the `AggregateLifecycle` class with it. So, things like `isLive`, `getVersion` and `markDeleted`. Especially the last one is pretty important if the life cycle of an aggregate actually ends.

**Comment by zambrovski** [comment]
> What is provided looks fine, but I am uncertain why you haven't added the other static operations from the `AggregateLifecycle` class with it. So, things like `isLive`, `getVersion` and `markDeleted`. Especially the last one is pretty important if the life cycle of an aggregate actually ends.

Since the methods `isLife()` and `getVersion` and `markDeleted` are static methods of `AggregateLifecycle` class, they can still be called from Kotlin by providing a static import and they neither collide with any Kotlin functions nor creating aliases would add any value (no reified classes, no functional support). 

So in Kotlin code it will look like:

```
import org.axonframework.modelling.command.AggregateLifecycle.*

class MyAggregate {

    @CommandHandler
    fun someHandler(cmd: SomeCommand) {
        
        if (isLive()) {
            val version = getVersion()
            // do something
        }
    }
    
    @EventSourcingHandler
    fun on(evt: SomeEvent) {
        // process event
        markDeleted()
    }
}
```

I see no value in providing the same functions and just change the import.

**Comment by smcvb** [comment]
Aaaah gotcha, I completely missed the point of collision in your original issue description. Could be me, could be the description; in the end it doesn't matter, as I feel that what you've done is fine as is. Thanks for clarifying @zambrovski.

**Review by smcvb — APPROVED** [review]
My concerns have been addressed, hence approving.

**Review by sandjelkovic — APPROVED** [review]
Looks good!

**Pull request merged**
